name: zile-tealeg
version: 2.4.11
summary: GNU Zile
description: |
  "GNU Zile is a text editor development kit, so that you can
  (relatively) quickly develop your own ideal text editor without
  reinventing the wheel for many of the common algorithms and
  data-structures needed to do so.

  It comes with an example implementation of a lightweight Emacs clone,
  called Zemacs. Every Emacs user should feel at home with
  Zemacs. Zemacs is aimed at small footprint systems and quick editing
  sessions (it starts up and shuts down instantly).

  More editors implemented over the Zile frameworks are forthcoming as
  the data-structures and interfaces improve: Zz an emacs inspired
  editor using Lua as an extension language; Zee a minimalist non-modal
  editor; Zi a lightweight vi clone; and more...

  Zile is a collection of algorithms and data-structures that currently
  support all basic Emacs-like editing features: it is 8-bit clean
  (though Unicode support is not ready yet), and the number of editing
  buffers and windows is only limited by available memoryand screen
  space respectively. Registers, minibuffer completion and auto fill are
  available.
  
  Zemacs implements a subset of Emacs with identical function and
  variable names, continuing the spirit of the earlier Zile editor
  implemented in C."
confinement: strict

apps:
  zile-tealeg:
    command: zile
    plugs:
      - home
parts:
  zile:
    plugin: autotools
    source: http://ftp.u-tx.net/gnu/zile/zile-2.4.11.tar.gz
    source-type: tar
    install-via: prefix
    build-packages:
      - pkg-config
      - libgc-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libtinfo-dev
      - help2man
    stage-packages:
      - libgc1c2
      - libncurses5
      - libncursesw5
      - libtinfo5
